name: Deploy Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'deployment environment'
        required: true
        type: choice
        default: ''
        options:
          - Test
          - Production
      tags:
        description: 'tags'
        required: false
        type: choice
        options: []

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.1
        id: set-result
        with:
          script: |
            const tags = await github.repos.listTags({
              owner: github.owner,
              repo: github.repository,
              per_page: 10
            });

            const tagNames = tags.data.map(tag => tag.name);
            return tagNames.join(',');
      - run: |
          echo tags--> ${{ steps.set-result }}
          echo owner github --> ${{ github.owner }}
          echo owner repository --> ${{ github.repository }}
          echo The deployment environment is ${{ inputs.environment }}