name: Deploy Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'deployment environment'
        required: true
        type: choice
        default: ''
        options:
          - Test
          - Production
      tags:
        description: 'tags'
        required: false
        type: choice
        options: []

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo tags--> ${{ steps.set-result }}
          echo owner github --> ${{ github.owner }}
          echo owner repository --> ${{ github.repository }}
          echo The deployment environment is ${{ inputs.environment }}
          tags=$(git describe --tags --all)
          echo "$tags"