name: Deploy Test

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: 'deployment environment'
        required: true
        type: choice
        options:
          - Test
          - Production
      tag:
        description: ''
        required: false
        type: string

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - run: echo The deployment environment is ${{ inputs.environment }}
      - run: echo The ref is ${{ github.ref }}
      - run: echo The ref_type is ${{ github.ref_type }}
      - run: echo The ref_name is ${{ github.ref_name }}

      - name: Deploy environment
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Please select a valid tag');
        if: (github.ref_type != 'tag') || (!startsWith(github.ref_name, 'test@'))

  build-test:
    needs: get-tags
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'test@') && inputs.environment == 'Test'
    runs-on: ubuntu-latest
    steps:
      - run: echo npm run build:test
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2
      - run: echo completed

  build:
    needs: get-tags
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'test@') && inputs.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - run: echo npm run build
